export const startPage = state => state.startPage
export const token = state => state.token
export const storeConditionPic = state => state.storeConditionPic
export const storeCondition = state => state.storeCondition
export const qualification = state => state.qualification
export const invoice = state => state.invoice
export const address = state => state.address
export const addressType = state => state.addressType
export const cartCount = state => state.cartCount
export const position = state => state.position
export const userInfo = state => state.userInfo
export const isLoading = state => state.isLoading
export const makeOrder = state => state.makeOrder
