export const SET_START_PAGE = 'SET_START_PAGE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_STORE_CONDITION = 'SET_STORE_CONDITION'
export const SET_STORE_CONDITION_PIC = 'SET_STORE_CONDITION_PIC'
